# GitHub workflow deploys Bundle assets (ML asset config and more)
# defined under mlops_stack_taxi_fares/assets/*
# and mlops_stack_taxi_fares/databricks.yml with prod deployment target configs,
# when PRs are merged into the release branch
name: Bundle Deployment for mlops_stack_taxi_fares Prod

on:
  push:
    branches:
      - 'release'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./mlops_stack_taxi_fares

env:
  DATABRICKS_TOKEN: ${{ secrets.PROD_WORKSPACE_TOKEN }}

jobs:
  prod:
    concurrency: mlops_stack_taxi_fares-prod-bundle-job
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v0.211.0
      - name: Validate Bundle For Prod
        id: validate
        run: |
          databricks bundle validate -t prod
      - name: Deploy Bundle to Prod
        id: deploy
        run: |
          databricks bundle deploy -t prod
